name: Update README with recent repositories

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate recent repositories section
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const user = 'jesuswasrasta';
          const perPage = 8; // number of repos to show
          // Fetch user's public, non-fork repos sorted by updated
          const repos = await github.paginate(github.rest.repos.listForUser, {
            username: user,
            per_page: 100,
            sort: 'created',
            direction: 'desc',
            type: 'owner'
          });
          console.log(`Fetched ${repos.length} repos for @${user}`);
          const filtered = repos
            .filter(r => !r.private)
            .sort((a,b) => new Date(b.created_at) - new Date(a.created_at))
            .slice(0, perPage);
          console.log(`Filtered to ${filtered.length} recent public repos`);
          let lines = filtered.map(r => {
            const desc = (r.description || 'No description').replace(/[\r\n]+/g, ' ').trim();
            const updated = new Date(r.updated_at).toISOString().slice(0,10);
            const forkTag = r.fork ? ' (fork)' : '';
            return `- [${r.name}](${r.html_url})${forkTag} — ${desc} (updated ${updated})`;
          });
          if (lines.length === 0) {
            lines = ['- No recent public repositories found.']
          }
          const fs = require('fs');
          const path = require('path');
          const readmePath = path.join(process.env.GITHUB_WORKSPACE, 'README.md');
          const start = '<!-- RECENT-REPOS:START -->';
          const end = '<!-- RECENT-REPOS:END -->';
          let readme = fs.readFileSync(readmePath, 'utf8');
          if (!readme.includes(start) || !readme.includes(end)) {
            throw new Error('Markers not found in README.md');
          }
          const newBlock = [start, ...lines, end].join('\n');
          const regex = new RegExp(`${start}[\s\S]*?${end}`);
          const updatedReadme = readme.replace(regex, newBlock);
          if (updatedReadme !== readme) {
            fs.writeFileSync(readmePath, updatedReadme);
            console.log('README.md updated with recent repositories.');
          } else {
            console.log('No changes to README.md needed.');
          }

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs(readme): update recent repositories section"
        file_pattern: README.md
        branch: master