name: Update README with recent repositories

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update README with recent repositories
      uses: codeSTACKr/readme-github-stats@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOW_LINES_OF_CODE: false
        SHOW_PROFILE_VIEWS: false
        SHOW_DAYS_OF_WEEK: false
        SHOW_TIMEZONE: false
        SHOW_EDITORS: false
        SHOW_LANGUAGE_PER_REPO: false
        SHOW_OS: false
        SHOW_PROJECTS: false
        SHOW_LOC_CHART: false
        SHOW_UPDATED: true